### ISSUE TITLE
No virtual servers

### ISSUE THREAD

**Issue by rbuelund** [virtualmin/virtualmin-messageoftheday#1]
Is this module functioning? I need exactly this kind of module, but when I install it it says: "No virtual servers have been created yet.", allthough there a lots of virtual servers on this machine ??

**Comment by jcameron** [comment]
Did you install the module into a system running Virtualmin?

**Comment by rbuelund** [comment]
Yes I did. I have now managed to create a message which is shown when I press the menuitem in Webmin (as admin) - but should it not be shown in the Dashboard of all Virtualmin users - or how does it actually work ?

**Comment by swelljoe** [comment]
It may be that Authentic theme doesn't display these messages, as it was written when Authentic didn't exist. I'm not sure where they show up, as I haven't looked at it in years. But, seems like it's probably useful. I don't see any indication it injects the message into any other pages, so that makes me think there was magic in the old Virtualmin framed theme that would pull it in if configured, maybe?

**Comment by rbuelund** [comment]
Soo.. nothing to do here or could it be implemented in the Authentic theme? I need this very much.. :-)

**Comment by jcameron** [comment]
@iliaross for the theme

**Comment by iliaross** [comment]
>  I need this very much.. :-)

If you need this very much, I will certainly have a look. Does this module work as expected in framed theme? If so, I will check what is wrong and fix it for Authentic Theme 19.70.

**Comment by rbuelund** [comment]
As it is now, it does not work in framed theme. But, then I don't really know if you are supposed to change some settings in the config of the theme to get it to show... as there is no description of the functionality of the module.

**Comment by rbuelund** [comment]
What I can though, is get it to show in webmin, when I am logged in as admin. If I go to "Webmin Configuration" - "Index Page Options" - "After login always go to module", and choose: Virtualmin Message of the Day
Then When I press the Webmin pane - the message whows. But not in Virtualmin, so I do not think this is the way to activate it ??

**Comment by iliaross** [comment]
> @jcameron @iliaross for the theme

Jamie, I remember you mentioned you wanted to fix this module on Virtualmin forum few weeks ago? Does that fix included this current problem?

**Comment by jcameron** [comment]
@rbuelund how were you hoping to use this module? Right now it's pretty basic, as it only displays the message to users who navigate to it.

**Comment by rbuelund** [comment]
Well I was actually hoping for the message to show up on the desktop of all virtualmin users on the server, so a kind of news messages that is shown to all users when they login.

**Comment by rbuelund** [comment]
No help ?

**Comment by iliaross** [comment]
You mean, an admin posts a _mod_ and all other server owners (including other admin users) can see it in notifications (right side slider), which can be pushed as a desktop notification (same way we notify at the moment about package updates)?

💡

**Comment by rbuelund** [comment]
Exactly that - I believe many admins could find that usefull - an example could be pushing messages out to users about important upcomming changes on the servers.

**Comment by rbuelund** [comment]
And the idea like in the module messages of the day with some html input, would be great as the admin then has the posibility to style the message the way he wants.

**Comment by iliaross** [comment]
> Exactly that - I believe many admins could find that usefull - an example could be pushing messages out to users about important upcomming changes on the servers..

I like the idea. @jcameron Jamie, could we just do it by pushing it to system status cache by adding a message and its timestamp, without using any extra modules, so we could deliver such functionality by simply reading `/etc/motd` file to all users who have access to the Dashboard?

> And the idea like in the module messages of the day with some html input, would be great as the admin then has the possibility to style the message the way he wants.

I don't think `/etc/motd` is meant for HTML but we could utilize noncanonical `/etc/motd.html` theoretically as well.

All we need is to read that file(s), cache them and display on the dashboard with dismiss button.

**Comment by rbuelund** [comment]
And now to make such module even better.. maybe there could be some kind of publish/unpublish function based on a start and end date field ? That would make it even more atractive ;-)

**Comment by iliaross** [comment]
Making a module is more work and doesn't seem necessary in this case?

What about just running `!edit /etc/motd` (from Authentic Theme navigation menu) to open it in an editor, clicking on the star next to the filename for adding it to the favorites for easy opening in the future?

**Comment by rbuelund** [comment]
Yes maybe - so I open a terminal with Alt+K, run the !edit /etc/motd.html and then in that window I add html or ? I do not really get it :-)

**Comment by rbuelund** [comment]
I believe if this is gonna be the solution, then there has to be some detailed description abouot setting it up, so that admins know that the possibility is there - but then it would be ok for me. But before it can work you have to change something to "push it to system status cache" - right ??

**Comment by iliaross** [comment]
>  so I open a terminal with Alt+K ..

Command shell interface to be exact. It doesn't have interaction yet (we should look into making it interactive sooner though).

> .. and then in that window I add html

I don't know as I don't understand what you're asking .. :smile: 

> so I open a terminal with Alt+K, run the !edit /etc/motd.html and then in that window I add html or ? I do not really get it :-)

As you edited a message as I was typing - in that command shell interface window you could type `edit  /etc/motd` to open an editor (you need `!` only when called from navigation menu), add a text, that other logged in users would see (via terminal (SSH) at the moment, as it's native to Linux).

> motd.html

If Jamie finds adding support for HTMLed version of _motd_ fine, then yes, as of now it will do nothing ..

**Comment by iliaross** [comment]
> I believe if this is gonna be the solution, then there has to be some detailed description abouot setting it up, 

What can be explained about setting up the _message of the day_ :slightly_smiling_face: ? The good thing, that if you know about this, you're just using it and Webmin will automatically catches things up and displays it on the Dashboard.

> But before it can work you have to change something to "push it to system status cache" - right ??

Yeah, it's pretty easy, and straight forward, compared to supporting old module, and what's more having a need installing it at the first place for making things work. Whereas, utilizing native Linux features is always best and fairly easy and fun to implement.

**Comment by rbuelund** [comment]
Ok - so for now I will wait until you say that the "push it to system status cache" has been added - right? Just to understand it completely ;-)

**Comment by iliaross** [comment]
Will discuss it with Jamie and update this ticket later.

**Comment by rbuelund** [comment]
Just perfect :-) Thanks so far - I will se if there is a little posible donation here :-) Where can one do that ?

**Comment by iliaross** [comment]
> Thanks so far - I will se if there is a little posible donation here :-) Where can one do that ?

You are welcome to buy Virtualmin Pro to support us.

**Comment by rbuelund** [comment]
Ahh - I think the company allready has that ;-) I am a freelancer.

**Comment by iliaross** [comment]
> Ok - so for now I will wait until you say that the "push it to system status cache" has been added - right? Just to understand it completely ;-)

I don't think we need any modules for that. `/etc/motd` has a very specific application and not used the same way by all distros.

If we want to distribute messages across all privileged (root/master admins) users, we could do it fairly easy by using a custom `/var/webmin/motd/username` files, and then pushing those messages from those files directly to a side notification bar and also make it pop-up as desktop notification.

I will look into adding it. I hope it's still needed.

**Comment by iliarostovtsev** [comment]
I think something line this will work:

![image](https://user-images.githubusercontent.com/4426533/141304466-8af348f9-51e1-40ed-8390-19c8ab3488c8.png)

**Comment by iliarostovtsev** [comment]
And to let an admin generate this kind of a message:
![image](https://user-images.githubusercontent.com/4426533/141304925-9ec218ce-2fa0-483b-a15a-cadc6d9baf7c.png)


.. for other admins with ease, there could be added a special _add notification_ button:

![image](https://user-images.githubusercontent.com/4426533/141305973-40b38ad3-1245-4fa5-b584-4e91b8df21dd.png)

**Comment by iliarostovtsev** [comment]
I think there is a better solution. With the next release an admin will be able to broadcast messages to all users on the system.

If exchanged among admins, it will be displayed in right notification slider. For other types of users it will be a popup.

All types of users will see desktop notification if allowed in a browser.

**Example:**

![image](https://user-images.githubusercontent.com/4426533/141654820-683d4eac-ab95-4341-adda-4856e45fca59.png)

![image](https://user-images.githubusercontent.com/4426533/141654812-119e48c7-baa4-404f-a6f7-2380f9f5d981.png)

**Comment by iliaross** [comment]
This feature has been fully finished and implemented.

It will be possible for master administrators to choose the group of users to which broadcast a message. All types of users will be able to see a desktop notification, if allowed in a browser, and a pop-up notification on UI as well.


**Examples:**

1. Click to compose -
![image](https://user-images.githubusercontent.com/4426533/141699983-2365b969-699b-48d7-89e5-5a10381a846f.png)

2. Enter the message and user group to send a message to -
![image](https://user-images.githubusercontent.com/4426533/141699909-40960885-3d74-4704-9002-d8c3c132a637.png)

3. Receive the message -
  3.1. Amins view -
![image](https://user-images.githubusercontent.com/4426533/141700196-e51f6211-6993-4419-872a-b8d795b861e7.png)
  3.2. All other users view - 
![image](https://user-images.githubusercontent.com/4426533/141700077-4e3d4895-f9ad-4edb-83ef-f97049561e9e.png)
  3.3. Desktop notification -
![image](https://user-images.githubusercontent.com/4426533/141700244-1cb73ecc-e058-46db-be1c-d66e2ff566c9.png)
